# ==============================
# Delphes Step - Signal Config
# ==============================
job:
  name_base: monojetDelphesStep
  work_dir: /users/ujeon/2025-monojet/MONOJET-WORKSPACE/src/Delphes

paths:
  input_parent:  /hdfs/user/ujeon/monojet/HepMC
  output_parent: /hdfs/user/ujeon/monojet/mc

# MX1 x lam1 x lam2 조합 전체
# 파일명: Signal_{mx1}_{lam1}_{lam2}.0.{process}.hepmc.gz
# process: 0 ~ 99

samples:
  Signal:
    - version: v1.0.0
      mx1:  [1-0, 1-5, 2-0, 2-5]
      lam1: [0-03, 0-05, 0-07, 0-08, 0-1, 0-15, 0-2, 0-3, 0-4, 0-5, 0-6, 0-7, 0-8, 0-9, 1-0]
      lam1: [0-04, 0-06,       0-08, 0-1, 0-15, 0-2, 0-3, 0-4, 0-5, 0-6, 0-7, 0-8, 0-9, 1-0]
      index: 0
      process: {min: 0, max: 99}
